feat: add support for python3.12
sendgrid/sendgrid-python pull request #1087
Opened 2024-08-24 03:40 UTC by meysam81

# Python3.12 #

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/sendgrid/sendgrid-python/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

2024-08-24 03:42 UTC, meysam81 commented
@tiwarishubham635 I don't have permission to assign a reviewer to the PR.
But here you are.
Please review.

2024-09-27 15:24 UTC, corbinday commented
@tiwarishubham635 any updates on this?

2025-04-11 11:19 UTC, tiwarishubham635 requested changes

2025-04-11 11:19 UTC, tiwarishubham635 commented on Makefile
> +	. venv/bin/activate; pip install -r test/requirements.txt
Can you tell me why do we need to change the makefile? I think we can skip this

2025-04-11 11:21 UTC, tiwarishubham635 commented
This looks good to me, just we can skip the Makefile change I feel. Also, can you add support for python 3.13 as well, else I'll have to raise a separate PR.

2025-04-12 03:28 UTC, meysam81 commented
@tiwarishubham635 

This pull request has been around for a year now.

For additional required changes, maintainers have access to modify the contents of this pull request. :point_down: 

![gh-pr](https://github.com/user-attachments/assets/12497932-5244-4f22-8fe4-6f1b65615236)

Cheers. :clinking_glasses:

2025-04-12 09:25 UTC, tiwarishubham635 commented
> @tiwarishubham635
> 
> This pull request has been around for a year now.
> 
> For additional required changes, maintainers have access to modify the contents of this pull request. 👇
> 
> ![gh-pr](https://private-user-images.githubusercontent.com/30233243/433002109-12497932-5244-4f22-8fe4-6f1b65615236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ0NTAxMjcsIm5iZiI6MTc0NDQ0OTgyNywicGF0aCI6Ii8zMDIzMzI0My80MzMwMDIxMDktMTI0OTc5MzItNTI0NC00ZjIyLThmZTQtNmYxYjY1NjE1MjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDEyVDA5MjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzN2RlNGM4NjY2YTJkMzI0MDE5MzA4YmMwNGYwZjU5MTVkNDUxOGM2OWQ5MWY4MjlmZDhmMDRjMjMyZjcwN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c60DJCJAQiZ390sxlSX5E1cesyqMG7twnVPJVxHYm_Y)
> 
> Cheers. 🥂

Thanks for this @meysam81! I have made the changes. One last thing before merging this. Is there any specific reason why we are adding [setuptools](https://github.com/sendgrid/sendgrid-python/pull/1087/files#diff-9c592cb90c321bcda4069ebf13a7b7f6c666f931a61fd01b98d00631dd113faaR8) to our requirements.txt?

2025-04-12 09:29 UTC, meysam81 commented
Yes, [this](https://github.com/sendgrid/sendgrid-python/pull/1087/files) is the reason 👇 

<img width="1285" alt="Screenshot 2025-04-12 at 16 27 16" src="https://github.com/user-attachments/assets/1356d3a2-3af1-4356-add0-98bec8dafb4c" />

2025-04-15 15:05 UTC, merged