Email activity API Documentation
sendgrid/sendgrid-python pull request #664
Opened 2018-10-09 13:51 UTC by dhoeric

# Fixes #562 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Add examples for Email Activity API
- Add usage for Email Activity API

If you have questions, please send an email to [SendGrid](mailto:dx@sendgrid.com), or file a GitHub Issue in this repository.

2018-10-09 13:52 UTC, SendGridDX commented
[![CLA assistant check](https://cla.sendgrid.com/pull/badge/not_signed)](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=664) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-python?pullRequest=664) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-python?pullRequest=664) it.</sub>

2018-10-23 17:48 UTC, thinkingserious commented
Hello @dhoeric,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

2018-10-23 17:49 UTC, thinkingserious commented
In addition to the updates requested by @misterdorm, 

Could you please merge this against our [v4 branch](https://github.com/sendgrid/sendgrid-python/tree/v4)? Thank you!

With Best Regards,

Elmer

2018-10-31 16:34 UTC, thinkingserious commented
Hello @dhoeric,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 6 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

2020-09-16 00:17 UTC, thinkingserious requested changes
Thank you for the PR once again! My apologies for the delayed code review.

2020-09-16 00:17 UTC, thinkingserious commented on USAGE.md
> +* [EMAIL ACTIVITY](#email-activity)
I think we should move this to the [use cases](https://github.com/sendgrid/sendgrid-python/tree/main/use_cases) directory. This file is auto-generated from our [OpenAPI specification](https://github.com/sendgrid/sendgrid-oai).

2020-11-09 17:04 UTC, childish-sambino commented
Closing due to inactivity. Please ping here if work is to continue.

2020-11-09 17:04 UTC, closed without merging